DROP TABLE IF EXISTS ticket_db;
DROP TABLE IF EXISTS user_account_db;
DROP TABLE IF EXISTS user_db;
DROP TABLE IF EXISTS event_db;

CREATE TABLE event_db (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_title VARCHAR(255) NOT NULL,
  event_date TIMESTAMP NOT NULL,
  event_ticket_price INTEGER
);

CREATE TABLE user_db (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name VARCHAR(255) NOT NULL,
  user_email VARCHAR(255) NOT NULL
);

CREATE TABLE user_account_db (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  user_amount INTEGER,
  CONSTRAINT fk_user_account_user FOREIGN KEY (user_id) REFERENCES user_db(id)
);

CREATE TABLE ticket_db (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  category VARCHAR(32),
  ticket_place INTEGER,
  CONSTRAINT fk_ticket_event FOREIGN KEY (event_id) REFERENCES event_db(id),
  CONSTRAINT fk_ticket_user FOREIGN KEY (user_id) REFERENCES user_db(id)
);

CREATE INDEX idx_user_name ON user_db(user_name);
CREATE INDEX idx_ticket_event ON ticket_db(event_id);
CREATE INDEX idx_ticket_user ON ticket_db(user_id);
